[project]
name = "rag-embs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "openai>=1.76.0",
    "pymongo>=4.12.0",
    "sentence-transformers>=4.1.0",
    "st-social-media-links>=0.1.5",
    "streamlit>=1.44.1",
]
